//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace be.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class complain
    {
        public int Id { get; set; }
        public string subject { get; set; }
        public string detail { get; set; }
        public int userId { get; set; }
    
        public virtual user user { get; set; }
    }
}
