//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace be.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public int Id { get; set; }
        public string eventname { get; set; }
        public string description { get; set; }
        public string place { get; set; }
        public Nullable<System.DateTime> eventdate { get; set; }
        public Nullable<System.TimeSpan> eventtime { get; set; }
        public string eventimage { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual user user { get; set; }
    }
}
