//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace be.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public string relation { get; set; }
        public string gender { get; set; }
        public Nullable<int> age { get; set; }
        public string profession { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual user user { get; set; }
    }
}
