//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace be.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectEntities1 : DbContext
    {
        public ProjectEntities1()
            : base("name=ProjectEntities1")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<advertise> advertises { get; set; }
        public virtual DbSet<complain> complains { get; set; }
        public virtual DbSet<@event> events { get; set; }
        public virtual DbSet<management> managements { get; set; }
        public virtual DbSet<member> members { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
